[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/files/docs/*"
  to ="https://3iq-webdocs.s3.ca-central-1.amazonaws.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/files/videos/*"
  to ="https://3iq-videos-web.s3.ca-central-1.amazonaws.com/:splat"
  status = 200
  force = true



[[redirects]]
  from = "https://3iq.ae/*"
  to = "https://3iq.io/ae/home"
  status = 301
  force = false
[[redirects]]
  from = "https://3iq.ca/*"
  to = "https://3iq.io/ca/home"
  status = 301
  force = false
[[redirects]]
  from = "https://3iq-us.com/*"
  to = "https://3iq.io/us/home"
  status = 301
  force = false
[[redirects]]
  from = "http://3iq.ae/*"
  to = "https://3iq.io/ae/home"
  status = 301
  force = false
[[redirects]]
  from = "http://3iq.ca/*"
  to = "https://3iq.io/ca/home"
  status = 301
  force = false
[[redirects]]
  from = "http://3iq-us.com/*"
  to = "https://3iq.io/us/home"
  status = 301
  force = false
[[redirects]]
  from = "https://www.3iq.ae/*"
  to = "https://3iq.io/ae/home"
  status = 301
  force = false
[[redirects]]
  from = "https://www.3iq.ca/*"
  to = "https://3iq.io/ca/home"
  status = 301
  force = false
[[redirects]]
  from = "https://www.3iq-us.com/*"
  to = "https://3iq.io/us/home"
  status = 301
  force = false
[[redirects]]
  from = "http://www.3iq.ae/*"
  to = "https://3iq.io/ae/home"
  status = 301
  force = false
[[redirects]]
  from = "http://www.3iq.ca/*"
  to = "https://3iq.io/ca/home"
  status = 301
  force = false
[[redirects]]
  from = "http://www.3iq-us.com/*"
  to = "https://3iq.io/us/home"
  status = 301
  force = false
